name: wheat3dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools<70
  - numpy<2
  - scipy
  - matplotlib
  - pillow
  - tqdm
  - pyyaml
  - plyfile
  - scikit-learn
  - shapely
  - ffmpeg
  - pytorch==2.1.2
  - torchvision==0.16.2
  - torchaudio==2.1.2
  - pytorch-cuda=12.1
  - pip:
      - hydra-core
      - omegaconf
      - wandb
      - opencv-python
      - segment-anything
      - gitpython
      - joblib
      - imageio
      - rich
      - ffmpeg-python
