_wandb:
    value:
        cli_version: 0.25.1
        e:
            wk3dmt7qmhz6w56ieyfvg73y3lzk72lq:
                args:
                    - -s
                    - ../Wheat3DGS-Yolo-SAM/data/plot_461
                    - -m
                    - ../Wheat3DGS-Yolo-SAM/data/plot_461/3dgs_output_res2_opt0_005_shd3_dui11000_dgt0_0002
                    - --resolution
                    - "2"
                    - --eval
                    - --iou_threshold
                    - "0.5"
                    - --exp_name
                    - run_1
                    - --vis_max_heads
                    - "10"
                    - --data_device
                    - cpu
                codePath: Wheat-3DGS/run_3d_seg.py
                codePathLocal: run_3d_seg.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "59589554176"
                email: pehd.eugster@gmail.com
                executable: /usr/bin/python
                git:
                    commit: f2a97b7f271787717e5d2ef1cae7a27c5e74c63e
                    remote: https://github.com/Patrick-Eugster/Bachelor_Thesis.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-25ab4bed-771a-4889-fc94-ce73bd3ab302
                host: 5f6be745636b
                memory:
                    total: "36776902656"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /workspace/Wheat-3DGS/run_3d_seg.py
                python: CPython 3.12.3
                root: /workspace/Wheat-3DGS
                startedAt: "2026-04-05T21:50:37.639544Z"
                writerId: wk3dmt7qmhz6w56ieyfvg73y3lzk72lq
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
exp_name:
    value: run_1
iou_threshold:
    value: 0.5
num_train_cameras:
    value: 30
resolution:
    value: 2
save_vis_overlay:
    value: true
total_masks:
    value: 7084
vis_max_heads:
    value: 10
