# @package _global_
defaults:
  - /dataset: fip              # override on CLI: dataset=phone
  - method: yolo_sam_v1        # override on CLI: method=yolo_sam_v2
  - _self_

experiment_name: "initial"
prepend_date: false

# run controls
limit_plots: 0
limit_images: 0
only_labeled_images: false
wandb_enabled: false

# hydra: don't create outputs/ folder, write log to logs/ instead
hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    handlers:
      file:
        filename: logs/main_v1.log
